certificate: /etc/detour/cert.pem
key: /etc/detour/key.pem
rules:
  - source: https://example.com
    destination: https://localhost:8000
  - source: http://subdomain.example.com
    destination: http://localhost:9000
